### ISSUE TITLE
Update example because foldl doesn't work

### ISSUE THREAD

**Issue by FranklinChen** [nomeata/list-fusion-probe#1]
https://github.com/nomeata/list-fusion-probe/blob/master/Data/List/Fusion/Probe.hs#L25 needs to be updated with a different example because `foldl` is fused, as you mentioned elsewhere at https://github.com/nomeata/list-fusion-probe/blob/master/tests/Test.hs#L18

**Comment by nomeata** [comment]
Right. Any suggestions? In the worst case I’ll simply add a note to the example that it refers to the pre-GHC-7.10-`foldl`.

**Comment by FranklinChen** [comment]
I don't know, maybe I'll think of something before I write about rewrite rules and mention `list-fusion-probe` in an upcoming "24 Days of Hackage" blog post...

**Comment by nomeata** [comment]
Oh, there is a dead line for this fix? Then let me at least push a clarifying comment to the docs...
