### ISSUE TITLE
Not in Stackage Nightly 2016-06-05

### ISSUE THREAD

**Issue by FranklinChen** [nomeata/list-fusion-probe#3]
Is there a reason `list-fusion-probe` is not in https://www.stackage.org/nightly-2016-06-05 ? It seems to build and test fine for me in that configuration.

**Comment by nomeata** [comment]
Did you have to force-override `list-fusion-probe`’s constraints? Probably, since it depends on base `< 4.9`. Did you run the test case? If you can confirm that it works as expected with ghc 8.0, I’ll update it.

**Comment by FranklinChen** [comment]
I was building what's on GitHub master, which allows base 4.9, not what's on Hackage, and everything was fine with

```
$ stack init --resolver=nightly
$ stack test
```

**Comment by nomeata** [comment]
Ah, great, so I just need to upload that. Thanks for the heads-up.
